version: '3'
services:
  caddy:
    image: caddy:2.2.1-alpine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime # Linux 下, 保持容器和宿主的时间和时区一致
      - ./Caddyfile:/etc/caddy/Caddyfile # 映射配置文件
      - ./caddy_data:/data # 数据
      - ./caddy_config:/config # 配置
    ports:
      - 80:80 # 宿主端口:容器端口
      - 443:443 # ssl
