version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/db:/data/db # 映射 postgre 的数据/配置地址，使得数据存储在本机硬盘
    ports:
      - 27017:27017   # postgres 默认端口 27017, 映射到本机的 27017