version: '3'
services:
  nginx_static:
    image: nginx:1.19.6-alpine
    restart: always
    working_dir: /home/static
    volumes:
       - ./html:/usr/share/nginx/html # 映射静态文件目录 hml 到容器
       - ./nginx.conf:/etc/nginx/nginx.conf # 映射 ginx 配置文件
    max-size: "200m"
    ports:
      - 10080:80 # 绑定容器的80端口到本的1080端口
